[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"

# AUR I Maintain / Co-Maintain #

[anime4k]
source = "github"
github = "bloc97/Anime4K"
use_latest_release = true
prefix = "v"

[bbg]
source = "github"
github = "bbg-contributors/bbg"
use_latest_release = true

[bbg-git]
source = "github"
github = "bbg-contributors/bbg"

[canokey-usbip-git]
source = "github"
github = "canokeys/canokey-usbip"

[docsify-cli]
source = "github"
github = "docsifyjs/docsify-cli"
use_latest_release = true
prefix = "v"

[dump1090-git]
source = "github"
github = "MalcolmRobb/dump1090"

[easierconnect]
source = "github"
github = "lyc8503/EasierConnect"

[easyeda-bin]
source = "regex"
url = "https://easyeda.com/page/download"
regex = 'easyeda-linux-x64-([\d.]+).zip'

[easyeda-pro-bin]
source = "regex"
url = "https://easyeda.com/page/download"
regex = 'easyeda-pro-linux-x64-([\d.]+).zip'

[easyeda-pro-electron]
source = "regex"
url = "https://easyeda.com/page/download"
regex = 'easyeda-pro-linux-x64-([\d.]+).zip'

[freerouting]
source = "github"
github = "freerouting/freerouting"
use_latest_release = true
prefix = "v"

[frida-dexdump]
source = "github"
github = "hluwa/frida-dexdump"
use_latest_release = true
prefix = "v"

[fscan]
source = "github"
github = "shadow1ng/fscan"
use_max_tag = true

[go-cqhttp-bin]
source = "github"
github = "Mrs4s/go-cqhttp"
use_latest_release = true
prefix = "v"

[gqrx]
source = "github"
github = "gqrx-sdr/gqrx"
use_latest_release = true
prefix = "v"

[gqrx-scanner]
source = "github"
github = "neural75/gqrx-scanner"
use_latest_release = true
prefix = "v"

[hid-ite8291r3-dkms-git]
source = "github"
github = "pobrn/hid-ite8291r3"

[iptv-checker]
source = "github"
github = "freearhey/iptv-checker"
use_latest_release = true
prefix = "v"

[jlc-assistant-bin]
source = "regex"
url = "https://www.jlc.com/portal/appDownloadsWithConfig.html"
regex = 'JLCPcAssit-linux-x64-([\d.]+).zip'

[lceda-pro]
source = "regex"
url = "https://lceda.cn/page/download"
regex = 'lceda-pro-linux-x64-([\d.]+).zip'

[lceda-pro-bin]
source = "regex"
url = "https://lceda.cn/page/download"
regex = 'lceda-pro-linux-x64-([\d.]+).zip'

[meanalyzer]
source = "github"
github = "platomav/MEAnalyzer"
use_latest_release = true

[mfoc-hardnested-git]
source = "github"
github = "nfc-tools/mfoc-hardnested"

[nixpkgs-fmt]
source = "github"
github = "nix-community/nixpkgs-fmt"
use_max_tag = true
prefix = "v"

[nuclei]
source = "github"
github = "projectdiscovery/nuclei"
use_latest_release = true
prefix = "v"

[nuclei-bin]
source = "github"
github = "projectdiscovery/nuclei"
use_latest_release = true
prefix = "v"

[python-ite8291r3-ctl-git]
source = "github"
github = "pobrn/ite8291r3-ctl"

[python-largestinteriorrectangle]
source = "github"
github = "OpenStitching/lir"
use_latest_release = true
prefix = "v"

[python-lzf]
source = "github"
github = "teepark/python-lzf"
use_max_tag = true
prefix = "release-"

[python-pipreqs]
source = "github"
github = "bndr/pipreqs"
use_max_tag = true
prefix = "v"

[python-rdbtools]
source = "github"
github = "sripathikrishnan/redis-rdb-tools"
use_latest_release = true
prefix = "rdbtools-"

[python-stitching]
source = "github"
github = "OpenStitching/stitching"
use_latest_release = true
prefix = "v"

[python-toml-sort]
source = "github"
github = "pappasam/toml-sort"
use_latest_release = true
prefix = "v"

[python-wallbreaker]
source = "github"
github = "hluwa/Wallbreaker"
use_latest_release = true

[python-yarg]
source = "github"
github = "kura/yarg"
use_max_tag = true

[srmd-ncnn-vulkan]
source = "github"
github = "nihui/srmd-ncnn-vulkan"
use_latest_release = true

[subfinder]
source = "github"
github = "projectdiscovery/subfinder"
use_latest_release = true
prefix = "v"

[subfinder-bin]
source = "github"
github = "projectdiscovery/subfinder"
use_latest_release = true
prefix = "v"

[ttf-vlgothic]
source = "github"
github = "daisukesuzuki/VLGothic"
use_latest_release = true

[whitesur-icon-theme]
source = "github"
github = "vinceliuice/WhiteSur-icon-theme"
use_latest_release = true
from_pattern = '(\d+)-(\d+)-(\d+)'
to_pattern = '\1.\2.\3'

# AUR dependencies #

[code-server]
source = "github"
github = "coder/code-server"
use_latest_release = true
prefix = "v"

[python-crccheck]
source = "github"
github = "MartinScharrer/crccheck"
use_latest_release = true
prefix = "v"

[python-pltable]
source = "pypi"
pypi = "pltable"

[whitesur-gtk-theme]
source = "github"
github = "vinceliuice/WhiteSur-gtk-theme"
use_latest_release = true
from_pattern = '(\d+)-(\d+)-(\d+)'
to_pattern = '\1.\2.\3'

# AUR I use #

[android-studio]
source = "regex"
url = "https://developer.android.com/studio"
regex = 'android-studio-([\d.]+)-linux.tar.gz'

[arduino-ide]
source = "github"
github = "arduino/arduino-ide"
use_latest_release = true

[burpsuite]
source = "regex"
url = "https://portswigger.net/burp/releases/community/latest"
regex = 'Professional / Community ([\d.]+)'

[charles]
source = "regex"
url = "https://www.charlesproxy.com/download/"
regex = 'v([\d.]+)'

[cinny-desktop]
source = "github"
github = "cinnyapp/cinny-desktop"
use_latest_release = true
prefix = "v"

[cloudflarespeedtest]
source = "github"
github = "XIU2/CloudflareSpeedTest"
use_latest_release = true
prefix = "v"

[cura]
source = "github"
github = "Ultimaker/Cura"
use_latest_release = true

[cyberchef-web]
source = "github"
github = "gchq/CyberChef"
use_latest_release = true
prefix = "v"

[davinci-resolve]
source = "regex"
url = "https://www.blackmagicdesign.com/support/partial/downloads"
regex = 'DaVinci Resolve ([\d.]+) Update'

[dirsearch]
source = "github"
github = "maurosoria/dirsearch"
use_latest_release = true
prefix = "v"

[dnsprobe]
source = "github"
github = "projectdiscovery/dnsprobe"
use_latest_release = true
prefix = "v"

[eagle]
source = "httpheader"
url = "https://www.autodesk.com/eagle-download-lin"
regex = 'EAGLE_([\d.]+)_English_Linux'
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

[gnome-shell-extension-blur-my-shell]
source = "github"
github = "aunetx/blur-my-shell"
use_latest_release = true
prefix = "v"

[gnome-shell-extension-clipboard-indicator]
source = "github"
github = "Tudmotu/gnome-shell-extension-clipboard-indicator"
use_max_tag = true
prefix = "v"

[gnome-shell-extension-dash-to-dock]
source = "github"
github = "micheleg/dash-to-dock"
use_latest_release = true
prefix = "extensions.gnome.org-v"

[gnome-shell-extension-gsconnect]
source = "github"
github = "GSConnect/gnome-shell-extension-gsconnect"
use_latest_release = true
prefix = "v"

[gnome-shell-extension-nightthemeswitcher]
source = "gitlab"
gitlab = "rmnvgr/nightthemeswitcher-gnome-shell-extension"
use_max_tag = true

[gnome-shell-extension-no-overview]
source = "github"
github = "fthx/no-overview"
use_max_tag = true
prefix = "v"

[gnome-shell-extension-system-monitor-next-git]
source = "github"
github = "mgalgs/gnome-shell-system-monitor-applet"

[google-chrome]
source = "cmd"
cmd = '''wget -qO- http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/other.xml.gz | zgrep -A1 "google-chrome-stable" | awk -F\" '/version/ {print $4"-"$6}' '''

[hexo-cli]
source = "github"
github = "hexojs/hexo-cli"
use_latest_release = true
prefix = "v"

[hmcl]
source = "github"
github = "huanghongxun/HMCL"
use_latest_release = true
prefix = "v"

[howdy]
source = "github"
github = "boltgolt/howdy"
use_latest_release = true
prefix = "v"

[hysteria]
source = "github"
github = "apernet/hysteria"
use_latest_release = true
prefix = "app/v"

[icalingua-plus-plus]
source = "github"
github = "Icalingua-plus-plus/Icalingua-plus-plus"
use_latest_release = true
prefix = "v"

[imhex]
source = "github"
github = "WerWolv/ImHex"
use_latest_release = true
prefix = "v"

[intellij-idea-ultimate-edition]
source = "regex"
url = "https://data.services.jetbrains.com/products/releases?code=IIU&latest=true&type=release"
regex = 'ideaIU-([\d.]+).tar.gz'

[kicad-library-ab2-git]
source = "github"
github = "ab2tech/KiCad"

[kicad-library-digikey-git]
source = "github"
github = "digikey/digikey-kicad-library"

[kicad-library-espressif-git]
source = "github"
github = "espressif/kicad-libraries"

[kicad-library-sparkfun-git]
source = "github"
github = "sparkfun/SparkFun-KiCad-Libraries"

[libnatspec]
source = "github"
github = "Etersoft/libnatspec"
use_max_tag = true

[linuxqq-nt-bwrap]
source = "regex"
url = "https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxQQDownload.js"
regex = 'QQ_([\d._-]+)_amd64'

[mfcuk-git]
source = "github"
github = "nfc-tools/mfcuk"

[mozc]
source = "github"
github = "google/mozc"
use_max_tag = true

[nbtexplorer]
source = "github"
github = "jaquadro/NBTExplorer"
use_latest_release = true
from_pattern = 'v(\d+).(\d+).(\d+)-win'
to_pattern = '\1.\2.\3'

[needrestart]
source = "github"
github = "liske/needrestart"
use_latest_release = true
prefix = "v"

[nixfmt]
source = "github"
github = "serokell/nixfmt"
use_latest_release = true
prefix = "v"

[nvidia-container-toolkit]
source = "github"
github = "NVIDIA/nvidia-container-toolkit"
use_latest_release = true
prefix = "v"

[openvisualtraceroute]
source = "github"
github = "leolewis/openvisualtraceroute"

[pacroller]
source = "github"
github = "isjerryxiao/pacroller"
use_max_tag = true

[paru]
source = "github"
github = "Morganamilo/paru"
use_latest_release = true
prefix = "v"

[pgloader]
source = "github"
github = "dimitri/pgloader"
use_max_tag = true
prefix = "v"

[pkcrack]
source = "regex"
url = "https://www.unix-ag.uni-kl.de/~conrad/krypto/pkcrack/download1.html"
regex = 'pkcrack-([\d.]+).tar.gz'

[pngcheck]
source = "regex"
url = "http://www.libpng.org/pub/png/apps/pngcheck.html"
regex = 'pngcheck-([\d.]+).tar.gz'

[pnpm-shell-completion]
source = "github"
github = "g-plane/pnpm-shell-completion"
use_latest_release = true
prefix = "v"

[pycharm-professional]
source = "regex"
url = "https://data.services.jetbrains.com/products/releases?code=PCP&latest=true&type=release"
regex = 'pycharm-professional-([\d.]+).tar.gz'

[python-frida]
source = "github"
github = "frida/frida"
use_latest_release = true

[python-frida-tools]
source = "github"
github = "frida/frida-tools"
use_max_tag = true

[python-iptvtools]
source = "github"
github = "huxuan/iptvtools"
use_latest_release = true
prefix = "v"

[python-librosa]
source = "github"
github = "librosa/librosa"
use_latest_release = true

[python-pluginbase]
source = "github"
github = "mitsuhiko/pluginbase"
use_max_tag = true
prefix = "v"

[python-pydub]
source = "github"
github = "jiaaro/pydub"
use_latest_release = true
prefix = "v"

[realsr-ncnn-vulkan]
source = "github"
github = "nihui/realsr-ncnn-vulkan"
use_latest_release = true

[sdrangel]
source = "github"
github = "f4exb/sdrangel"
use_latest_release = true
prefix = "v"

[seclists]
source = "github"
github = "danielmiessler/SecLists"
use_latest_release = true

[sedutil]
source = "github"
github = "Drive-Trust-Alliance/sedutil"
use_max_tag = true

[slack-desktop]
source = "regex"
url = "https://slack.com/downloads/instructions/linux"
regex = 'slack-([\d.-]+).el8.x86_64.rpm'

[stm32cubeide]
source = "regex"
url = "https://nvchecker.apeiria.net/stm32cubeide"
regex = 'STM32CubeIDE-Lnx.version=([\d.]+).html'

[stm32cubemonitor]
source = "regex"
url = "https://nvchecker.apeiria.net/stm32cubemonitor"
regex = 'STM32CubeMon-Lin.version=([\d.]+).html'

[stm32cubemx]
source = "regex"
url = "https://nvchecker.apeiria.net/stm32cubemx"
regex = 'STM32CubeMX-Lin.version=([\d.]+).html'

[subconverter]
source = "github"
github = "tindy2013/subconverter"
use_latest_release = true
prefix = "v"

[tcping]
source = "github"
github = "zhengxiaowai/tcping"
use_max_tag = true

[ulauncher]
source = "github"
github = "Ulauncher/Ulauncher"
use_latest_release = true

[v2raya]
source = "github"
github = "v2rayA/v2rayA"
use_latest_release = true
prefix = "v"

[ventoy]
source = "github"
github = "ventoy/Ventoy"
use_latest_release = true
prefix = "v"

[video2x]
source = "github"
github = "k4yt3x/video2x"
use_latest_release = true

[visual-studio-code]
source = "httpheader"
url = "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
regex = 'code_([\d.]+)-\d+_amd64.deb'

[wafw00f]
source = "github"
github = "EnableSecurity/wafw00f"
use_latest_release = true
prefix = "v"

[wemeet]
source = "htmlparser"
url = "https://source.meeting.qq.com/download-center.html"
xpath = """//div[contains(@class, 'linux')]//div[contains(@class, 'with-version')]/div"""
prefix = "版本号："

[whisper]
source = "github"
github = "openai/whisper"
use_latest_release = true
prefix = "v"

[whisper-cpp]
source = "github"
github = "ggerganov/whisper.cpp"
use_latest_release = true
prefix = "v"

[whitesur-cursor-theme-git]
source = "github"
github = "vinceliuice/WhiteSur-cursors"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"
