[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[anime4k]
source = "github"
github = "bloc97/Anime4K"
use_latest_release = true
prefix = "v"

[bbg]
source = "github"
github = "bbg-contributors/bbg"
use_latest_release = true

[code-server-marketplace]
source = "github"
github = "coder/code-server"
use_latest_release = true
prefix = "v"

[docsify-cli]
source = "github"
github = "docsifyjs/docsify-cli"
use_latest_release = true
prefix = "v"

[easierconnect]
source = "github"
github = "lyc8503/EasierConnect"

[easyeda-bin]
source = "regex"
url = "https://easyeda.com/page/download"
regex = 'easyeda-linux-x64-(\d+.\d+.\d+).zip'

[easyeda-pro-bin]
source = "regex"
url = "https://easyeda.com/page/download"
regex = 'easyeda-pro-linux-x64-(\d+.\d+.\d+).zip'

[easyeda-pro-electron]
source = "regex"
url = "https://easyeda.com/page/download"
regex = 'easyeda-pro-linux-x64-(\d+.\d+.\d+).zip'

[frida-dexdump]
source = "github"
github = "hluwa/frida-dexdump"
use_latest_release = true
prefix = "v"

[fscan]
source = "github"
github = "shadow1ng/fscan"
use_latest_release = true

[go-cqhttp-bin]
source = "github"
github = "Mrs4s/go-cqhttp"
use_latest_release = true
prefix = "v"

[gqrx-scanner]
source = "github"
github = "neural75/gqrx-scanner"
use_latest_release = true
prefix = "v"

[jlc-assistant-bin]
source = "regex"
url = "https://www.jlc.com/portal/appDownloadsWithConfig.html"
regex = 'JLCPcAssit-linux-x64-(\d+.\d+.\d+).zip'

[lceda-pro]
source = "regex"
url = "https://lceda.cn/page/download"
regex = 'lceda-pro-linux-x64-(\d+.\d+.\d+).zip'

[lceda-pro-bin]
source = "regex"
url = "https://lceda.cn/page/download"
regex = 'lceda-pro-linux-x64-(\d+.\d+.\d+).zip'

[nuclei]
source = "github"
github = "projectdiscovery/nuclei"
use_latest_release = true
prefix = "v"

[nuclei-bin]
source = "github"
github = "projectdiscovery/nuclei"
use_latest_release = true
prefix = "v"

[python-lzf]
source = "github"
github = "teepark/python-lzf"
use_max_tag = true
prefix = "release-"

[python-pem]
source = "github"
github = "hynek/pem"
use_max_tag = true

[python-rdbtools]
source = "github"
github = "sripathikrishnan/redis-rdb-tools"
use_latest_release = true
prefix = "rdbtools-"

[python-wallbreaker]
source = "github"
github = "hluwa/Wallbreaker"
use_latest_release = true

[subfinder]
source = "github"
github = "projectdiscovery/subfinder"
use_latest_release = true
prefix = "v"

[subfinder-bin]
source = "github"
github = "projectdiscovery/subfinder"
use_latest_release = true
prefix = "v"

[whitesur-icon-theme]
source = "github"
github = "vinceliuice/WhiteSur-icon-theme"
use_latest_release = true
from_pattern = '(\d+)-(\d+)-(\d+)'
to_pattern = '\1.\2.\3'

# [mastodon-twitter-sync]
# source = "github"
# github = "klausi/mastodon-twitter-sync"
# use_latest_release = true
# prefix = "v"

# [lceda-bin]
# source = "regex"
# url = "https://lceda.cn/page/download"
# regex = 'lceda-linux-x64-(\d+.\d+.\d+).zip'
